# Generated by Django 3.2.9 on 2021-12-24 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartfarm_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileuploadmodel',
            name='title',
        ),
    ]
