# Generated by Django 4.0.1 on 2022-01-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartfarm_page', '0002_remove_fileuploadmodel_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputValueModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chojang', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Kids_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=10)),
                ('Center_name', models.TextField(max_length=20)),
            ],
            options={
                'db_table': 'kids_db',
            },
        ),
        migrations.AlterField(
            model_name='fileuploadmodel',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
