# Generated by Django 3.2.9 on 2022-01-27 05:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartfarm_page', '0002_remove_fileuploadmodel_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InputValueModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chojang', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumberRegex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(regex='?([0-9]{3,4})-?([0-9]{4})$')])),
            ],
        ),
        migrations.AlterField(
            model_name='fileuploadmodel',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
