# Generated by Django 3.2.9 on 2022-02-09 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartfarm_page', '0003_auto_20220127_1457'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
