# Generated by Django 3.2.9 on 2022-02-09 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartfarm_page', '0003_auto_20220127_1457'),
        ('smartfarm_page', '0004_all_allkids_delete_kids_data'),
    ]

    operations = [
    ]
